//DO NOT CHANGE ANYTHING EXCEPT ADDING LINES TO THE Changelog

LET vLastReload = ReloadTime() - 4/24;

Changelog:
Load *,RowNo() as ID;
Load * Inline [
Version,Author,Date,Change
1.0,Cullin,3/27/2020,Creating initial app and visuals
1.1,Taj,3/27/2020,Test changelog capability
1.2,Mike,3/31/2020,Fixing reload timezone in changelog
];


LET vAppVersion = Peek('Version', NoOfRows('Changelog')-1, 'Changelog');
LET vCurrentDev = Peek('Author', NoOfRows('Changelog')-1, 'Changelog');

//test PR